services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - bot-data:/data
    environment:
      - SQLITE_DB_PATH=/data/bot.db
    logging:
      options:
        max-size: "1M"
        max-file: "10"

volumes:
  bot-data:
