name: Nyan Bot

on:
  push:
    branches:
      - master
      - '!*no-ci*'
      - '!*skip-ci*'
    tags:
      - 'v*'
      - '!*no-ci*'
      - '!*skip-ci*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv==2024.4.1
        pipenv install --dev
    - name: Lint
      run: pipenv run make lint
    - name: Test with pytest
      run: export PYTHONPATH=./bot && pipenv run pytest
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: vldc-hq/vldc-bot/bot
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ghcr.io
        dockerfile: compose/prod/Dockerfile
    - name: Trigger deploy
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY_PROD }}
      run: |
        curl --fail --insecure --max-time 300 "https://$DEPLOY_HOST/deploy/bot-prod?secret=$DEPLOY_KEY"'&sync=true'
